=== Testik207/Sugupuu/wwwroot/minuSugupuu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sugupuu"><xs:complexType><xs:sequence><xs:element ref="inimene"/></xs:sequence></xs:complexType></xs:element>
  <xs:element name="inimene" type="inimeseTuup"/>
  <xs:complexType name="inimeseTuup">
    <xs:sequence>
      <xs:element name="nimi" type="xs:string"/>
      <xs:element name="roll" type="xs:string"/>
      <xs:element name="lapsed" minOccurs="0">
        <xs:complexType><xs:sequence>
          <xs:element ref="inimene" maxOccurs="unbounded"/>
        </xs:sequence></xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="synd" type="xs:gYear" use="required"/>
    <xs:attribute name="elukoht" type="xs:string" use="required"/>
  </xs:complexType>
</xs:schema>

=== Testik207/Sugupuu/wwwroot/MinuSugupuu.xml
<?xml version='1.0' encoding='UTF-8'?>
<sugupuu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="minuSugupuu.xsd">
  <inimene synd="1949" elukoht="Tallinn">
    <nimi>Tomara</nimi>
    <roll>vanaema</roll>
    <lapsed>
      <inimene synd="1967" elukoht="Tallinn">
        <nimi>Oksana</nimi>
        <roll>ema</roll>
        <lapsed>
          <inimene synd="1990" elukoht="Tallinn">
            <nimi>Julja</nimi>
            <roll>õde</roll>
            <lapsed>
              <inimene synd="2020" elukoht="Tallinn">
                <nimi>Alja</nimi>
                <roll>õe tütar</roll>
              </inimene>
            </lapsed>
          </inimene>
          <inimene synd="1993" elukoht="Tallinn">
            <nimi>Igor</nimi>
            <roll>vend</roll>
          </inimene>
          <inimene synd="2005" elukoht="Tallinn">
            <nimi>Timur</nimi>
            <roll>mina</roll>
          </inimene>
        </lapsed>
      </inimene>
    </lapsed>
  </inimene>
</sugupuu>
